name: todo_app
description: A To-Do list app with Hive and Provider

# تحديد البيئة المطلوبة للإصدار
environment:
  sdk: ">=3.5.0 <4.0.0"  # أو يمكن تحديد إصدار مناسب حسب نسختك من Flutter

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.0.0
  hive_flutter: ^1.1.0
  provider: ^6.0.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  build_runner: ^2.1.0
  hive_generator: ^1.1.0
  flutter_test:
    sdk: flutter
